# Generated by Django 4.2.5 on 2023-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
                (
                    "image_id",
                    models.UUIDField(db_index=True, verbose_name="ID картинки"),
                ),
                (
                    "image_webp",
                    models.ImageField(
                        upload_to="", verbose_name="ссылка на картинку в формате webp"
                    ),
                ),
                (
                    "image_crop",
                    models.ImageField(
                        upload_to="",
                        verbose_name="ссылка на сжатую до 300*300px картинку в формате webp",
                    ),
                ),
                (
                    "image_base64",
                    models.TextField(
                        blank=True, null=True, verbose_name="картинка в base64"
                    ),
                ),
                (
                    "is_created",
                    models.BooleanField(
                        default=False, verbose_name="фото на сервере созданы"
                    ),
                ),
            ],
            options={
                "verbose_name": "картинка",
                "verbose_name_plural": "картинки",
            },
        ),
    ]
