version: "3.8"

services:

  postgres_db:
    image: postgres:15-alpine
    restart: always    
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - upload_postgresql_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: >
          --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    entrypoint: [ "sh", "-c", "celery -A backend worker --loglevel=info --concurrency 1 -E" ]
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres_db

  nginx:
    image: nginx:latest
    container_name: todo_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    network_mode: host


volumes:
  upload_postgresql_volume: